### ISSUE TITLE
Minimize alert block display time.

### ISSUE THREAD

**Issue by AjithLalps** [kartik-v/yii2-widget-alert#13]
Please tell me how to reduce the display time of alert blocks.

**Comment by DBX12** [comment]
You can set the `delay` setting to a value fitting your needs. It should look like this:

```php
echo Alert::widget([
        'type' => Alert::TYPE_INFO,
        'body' => 'This is an informative alert',
        'delay' => 1000 /* This will close the alert after 1000 ms */ 
]);
```

There are a few more settings, you can see them here: https://github.com/kartik-v/yii2-widget-alert#demo (use the two links in this block)
