### ISSUE TITLE
Release v1.1.1 

### ISSUE THREAD

**Issue by DBX12** [kartik-v/yii2-widget-alert#14]
This is not a technical question or bug report, so I allowed myself to remove the pre-set issue text.

Dear Kartik,
could you please make a new release, so we can update it through composer? I got v1.1.0 via composer and you fixed so many things meanwhile. I don't want to patch it local via copy and paste from the repo here as this surely will be bad practice. 

Thank you for your great work!

**Comment by kartik-v** [comment]
Done.
