### ISSUE TITLE
AlertBlock type growl not shown & how to setup flash messages

### ISSUE THREAD

**Issue by dadinugroho** [kartik-v/yii2-widget-alert#15]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-widget-alert.
- [X ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/widget-details/alert).
- [ X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.  In controller, add this line
`Yii::$app->getSession()->setFlash('success', $name . Yii::t('app', ' is successfully deleted.'));`

Somehow, I cannot use array on flash message.

2. In view, I add this line in gridview generated by johnivtn -> ajaxcrud.
`'panel' => [
                'type' => 'primary',
                'heading' => Html::icon('glyphicon glyphicon-list') . ' ' . Yii::t('app', '{title} listing', ['title' => $this->title, 'titleId' => strtolower($this->title)]),
                'before' => AlertBlock::widget([
                    'useSessionFlash' => true,
                    'type' => AlertBlock::TYPE_GROWL
                ]),`

But nothing is shown

## Expected behavior and actual behavior

I was expecting to see the growl like notification but nothing. Actually, I can display it if it is alert not growl.

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [X] Windows
- [ ] Mac OS X
- [X ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-widget-alert version:

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/widget-details/alert)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-alert without other plugins.

TIA

Daniel

**Comment by blupointmedia** [comment]
@dadinugroho did you ever get this working? I am having the same issue as well.

**Comment by dadinugroho** [comment]
@blupointmedia no. still not working....
