### ISSUE TITLE
Cannot use yii\bootstrap\Alert as Alert because the name is already in use

### ISSUE THREAD

**Issue by jobsrey** [kartik-v/yii2-widget-alert#19]
I got issue after update.

![image](https://user-images.githubusercontent.com/25948056/51957938-44c9cb00-2480-11e9-8c41-48471aaf8df8.png)

how to fix this problem, thx kartik..

**Comment by kartik-v** [comment]
You do not seem to have the latest code or the extension. Cross check your app dependencies with the repo and run a proper composer update.

**Comment by fabiomlferreira** [comment]
I have exactly the same problem, and I'm using version 1.1.3, and I get this error if I downgrade to 1.1.1 it works.

**Comment by kartik-v** [comment]
Please [read the documentation for configuring your bootstrap version](https://demos.krajee.com/widget-details/alert#bs-info).

**Comment by mavs1971** [comment]
As of today, with a clean installation of yii2, it keeps giving me this error exactly the same. Kartik if you can guide me if I am installing correctly from composer
![imagen](https://user-images.githubusercontent.com/13508859/84102180-b8b5a500-a9dd-11ea-942c-6b7e3bc17942.png)
 mi json file is 
"minimum-stability": "dev",
  "require": {
   "php": ">=5.6.0",
    "yiisoft/yii2": "~2.0.14",
    "yiisoft/yii2-bootstrap": "~2.0.0",
    "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
    "mavs1971/yii2-mavsuser": "*",
    "abhi1693/yii2-config": "1.0.0",
    "abhi1693/yii2-installer": "*",
    "abhi1693/yii2-system-info": "*",
    "raoul2000/yii2-bootswatch-asset": "*",
    "kartik-v/yii2-widget-sidenav": "*",
    "kartik-v/yii2-widget-alert": "*",
    "wbraganca/yii2-dynamicform": "*",
    "kartik-v/yii2-grid": "@dev",
    "2amigos/yii2-date-picker-widget": "@dev",
    "kartik-v/yii2-mpdf": "*",
    "kartik-v/yii2-widget-select2": "@dev",
    "kartik-v/yii2-widget-activeform": "@dev",
    "kartik-v/yii2-widgets": "*",
    "kartik-v/yii2-field-range": "*",
    "himiklab/yii2-recaptcha-widget": "*",
    "2amigos/yii2-ckeditor-widget": "*",
    "dmstr/yii2-adminlte-asset": "^2.1",
    "schmunk42/yii2-giiant": "@stable",
    "cornernote/yii2-linkall": "*",
    "buttflattery/yii2-formwizard": "@dev"
  },
  
  "require-dev": {
    "yiisoft/yii2-codeception": "*",
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*"
  },
  "config": {
    "process-timeout": 1800
  },
  "extra": {
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    },

    "branch-alias": {
        "dev-master": "1.1.x-dev"
    }

**Comment by kartik-v** [comment]
As mentioned before, if you are using bootstrap 4 --- configure your `bsVersion` to `4.x` in yii2 params appl config file `params.php`  as [described here](https://demos.krajee.com/widget-details/alert#bs-info) - if you are using bootstrap 3 set it to `3.x` - remember you must install the right yii2 bootstrap extension `yii2-bootstrap4` for `4.x` or yii2-bootstrap` for `3.x`.
