### ISSUE TITLE
Growl requirement

### ISSUE THREAD

**Issue by craiglondon** [kartik-v/yii2-widget-alert#21]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-widget-alert.
- [x ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/widget-details/alert).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [n] I have included a failing test as a pull request (Optional).

I was reviewing the diff from v1.1.2 to master and I noticed the composer.json was modified to require a newer version of Growl.  On Growl v1.1.3 does not exist

    "require": {
        "kartik-v/yii2-widget-growl": ">=1.1.2"	        "kartik-v/yii2-widget-growl": ">=1.1.3"
    },	    },

https://github.com/kartik-v/yii2-widget-alert/compare/v1.1.2...master

https://github.com/kartik-v/yii2-widget-growl/releases

**Comment by gabriellaborghi** [comment]
Now growl is at 1.1.1 version, but  kartik-v /yii2-widget-alert requires >=1.1.2
https://packagist.org/packages/kartik-v/yii2-widget-alert
I can't install it.
