### ISSUE TITLE
Render Problem

### ISSUE THREAD

**Issue by abhi1693** [kartik-v/yii2-widget-alert#3]
Whenever an alert is displayed and at the same time if the mouse is moved on the screen, the alert starts flickering. Although there are no errors generated, so my guess is that there is some rendering problem with fade out.

Please take a look into this. Thank you..

**Comment by kartik-v** [comment]
You can set the `delay` property to various values and try what works for you. For example setting it to `0` or `false` will disable fade effect for the alert.
