### ISSUE TITLE
Install Growl automatically

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-alert#4]
It seems that it's intentional that Alert Block does not install Growl automatically with itself (based on the composer.json file). I suggest installing Growl automatically to avoid the need for troubleshooting after installation. For the record, I tried installing Alert Block with composer via command line using "*" and "dev-master" and in both cases it gave the following error message:
```
The class '\kartik\growl\Growl' was not found and is required for rendering Growl notifications in the alert block.

Please ensure you have installed the 'yii2-widget-growl' extension. To install, you can run this console command from your application root:

php composer.phar require kartik-v/yii2-widget-growl: "@dev"
```
Eventually I installed Growl manually and it worked fine.

**Comment by kartik-v** [comment]
Yes, its to ensure that people who need to use the extension without growl OR who DO NOT NEED Growl, can install as is, and use as is like a normal bootstrap alert (which is the default one used by Yii as well). Those who need the extension with growl need to install growl manually.

The exception message has been made as obvious as possible (for folks trying to use growl without installing it).

**Comment by YasserHassan** [comment]
Yes the message is clear but I thought it was a backup measure in case something missed during installation (e.g. incorrect composer.json) not the normal installation scenario as with your other extensions because it showed up as an exception. Good though to have the ability to leave Growl out if not required. It would be good to include it explicit in the installation procedure as an optional step for who need it. I sent you a pull request for this.

**Comment by loveorigami** [comment]
@YasserHassan see https://github.com/loveorigami/yii2-notification-wrapper
for change layer Growl to Noty or more...
